# Generated by Django 5.2.1 on 2025-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0039_alter_ticketchange_field")
    ]

    operations = [
        migrations.RunSQL(
            sql="USE information_schema;"
        ),
        migrations.RunSQL(
            sql="SET @cn=(select CONSTRAINT_NAME from check_constraints WHERE check_clause = '(order >= 0)');",
        ),
        migrations.RunSQL(
            sql="USE helpdesk;",
        ),
        migrations.RunSQL(
            sql="SET @s = CONCAT('ALTER TABLE helpdesk_kbitem DROP CHECK ', @cn, ';');",
        ),
        migrations.RunSQL(
            sql="PREPARE stmt FROM @s;"
        ),
        migrations.RunSQL(
            sql="EXECUTE stmt;",
            reverse_sql="ALTER TABLE helpdesk_kbitem ADD CONSTRAINT kbitem_check_order_gte_zero CHECK (order >= 0)"
        )
    ]