# Generated by Django 5.2.1 on 2025-06-02 09:56

from django.db import migrations, models

from helpdesk.templatetags.helpdesk_staff import helpdesk_staff


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0041_add_is_agent_field")
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequests",
            fields=[
                (
                    "branch",
                    models.CharField(
                        verbose_name="PR Branch",
                        primary_key=True,
                        help_text="Agent created branch which needs to be merged, or discarded.",
                        max_length=64,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        verbose_name="PR Intent",
                        max_length=512,
                        null=False,
                        blank=False,
                        help_text="Description of what the agent was attempting to do in this PR."
                    )
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        verbose_name="PR Creation date",
                        blank=False,
                        null=False,
                        help_text="Date this pr was created."
                    ),
                ),
                (
                    "resolution_date",
                    models.DateTimeField(
                        verbose_name="PR Resolution Date",
                        blank=True,
                        null=True,
                        help_text="Date this pr was merged or discarded."
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        verbose_name="PR Status",
                        help_text="1. Open, 2. Merged, 3. Discarded",
                        blank=1,
                        default=1,
                        choices=[
                            (1, "1. Open"),
                            (2, "2. Merged"),
                            (3, "3. Discarded"),
                        ]
                    ),
                )
            ]
        )
    ]