# Generated by Django 5.2.1 on 2025-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0042_pull_requests")
    ]

    operations = [
        migrations.RunSQL(
            sql='''
CREATE PROCEDURE FinishSession(branch_name VARCHAR(64), intent VARCHAR(512))
BEGIN
  CALL dolt_checkout(branch_name);
  SET @changes = (SELECT count(*) FROM dolt_status);
  SET @create_pr = 0;

  IF @changes > 0 THEN
    CALL dolt_commit('-Am', @intent);
    SET @create_pr = 1;
  ELSE
    SET @branch_hash = (SELECT hash FROM dolt_branches WHERE name = branch_name);
    SET @branch_head_in_main = (SELECT count(*) FROM dolt_log('main') WHERE commit_hash = @branch_hash);

    IF @branch_head_in_main = 1 THEN
      CALL dolt_checkout('main');
      CALL dolt_branch('-d', branch_name);
    ELSE
      SET @create_pr = 1;
    END IF;
  END IF;
      
  IF @create_pr = 1 THEN
      CALL dolt_checkout('main');
      INSERT INTO helpdesk_pullrequests (branch, intent, creation_date, status) VALUES (@branch_name, @intent, now(), 1);
  END IF;
END
'''
        ), migrations.RunSQL(sql='''CALL dolt_commit('-Am', 'created FinishSession stored proc');'''),
    ]