# Generated by Django 5.2.1 on 2025-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0043_finish_session_stored_proc")
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE PROCEDURE MergePR(branch_name VARCHAR(64))
                BEGIN
                    CALL dolt_checkout('main');
                    SET @changes = (SELECT count(*) FROM dolt_status);

                    IF @changes > 0 THEN
                        CALL dolt_commit('-Am', 'pre-merge commit');
                    END IF;

                    CALL dolt_merge(branch_name);
                    UPDATE helpdesk_pullrequests SET status = 2, resolution_date = now() WHERE branch = branch_name;
                    CALL dolt_commit('-Am', 'post-merge commit');
                END
                '''
        ), migrations.RunSQL(sql='''CALL dolt_commit('-Am', 'created MergePR stored proc');'''),
    ]